#!/bin/bash
protected_branch='master'
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [ $protected_branch = $current_branch ]
then
	read -p "You're about to push to master. What's the meaning of life? > " -n 2 -r < /dev/tty
    if echo $REPLY | grep -E '42' > /dev/null
    then
    	exit 0 # carry on
    fi
	echo "fail aborting ..."
    exit 1 # exit and go read a book
else
    exit 0
fi
