#!/bin/bash

bold=$(tput bold)
normal=$(tput sgr0)

echo "${bold}[pre-push] Pulling in latest changes from master...${normal}"
git pull origin master

echo "${bold}[pre-push] setting up jenkins docker container...${normal}"
cd jenkins/
sudo docker-compose down
sudo docker-compose build
sudo docker-compose up -d 
sleep 5 # Give Jenkins a second to start
echo "${bold}[pre-push] running jenkins_build_script...${normal}"
../.githooks/jenkins_build
EXIT=$?

echo "${bold}[pre-push] Tearing down jenkins...${normal}"
sudo docker-compose down
exit $EXIT